language: node_js
node_js:
  - "8"
branches:
  only:
  - master
addons:
  apt:
    packages:
    - gcc
    - libgmp-dev
    - libmpfr-dev
    - python2.7
before_install:
  - npm i -g npm@6.5.0
  - gcc -v
cache: npm
before_script:
  - mkdir build
  - cp node_modules/giac/Release/giac.node build/giac.node
  - npm install -g jest